version: '3'

services:
  nextjs: 
    build: ./
    restart: always

  nginx: 
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    restart: always