version: '3'

services:
  nextjs: 
    build: ./
    restart: always

  nginx: 
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ~/etc/letsencrypt/:/etc/letsencrypt/
    restart: always